# Generated by Django 3.1.4 on 2020-12-07 23:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_card_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='solicitation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
