name: Python application

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: ['5432:5432']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Copying configurations
      run: |
        cp contrib/env-sample .env
    - name: Install dependencies
      run: |
        pip install -q -r requirements-dev.txt
    - name: Lint with flake8
      run: |
        flake8 .
    - name: Test with pytest
      run: |
        pytest gypz --cov=gypz
    - name: Posting Coverage
      env:
        CODECOV_TOKEN: "2f12e3d1-36c7-4325-81c7-b0b16ea1d3b1"
      run: |
        codecov